# Generated by Django 5.2.7 on 2025-12-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='External URL (optional, used if no page is selected)', null=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, help_text='Link to a page (optional if this is a dropdown parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent navigation item (leave empty for top-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.navigationitem')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
