# Generated by Django 5.2.7 on 2025-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('INSTITUTIONAL', 'Institutional'), ('COMMUNITY_PARTNER', 'Community Partner'), ('WELLNESS_PARTNER', 'Wellness Partner'), ('KEYSTONE', 'Keystone'), ('PLATINUM', 'Platinum'), ('TITANIUM', 'Titanium'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=255),
        ),
    ]
