# Generated by Django 5.2.7 on 2025-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide this sponsor'),
        ),
    ]
