# Generated by Django 5.2.7 on 2025-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsor_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='ribbon_visible',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide the PAO ribbon', verbose_name='Ribbon Toggle'),
        ),
    ]
