# Generated by Django 5.2.7 on 2026-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_remove_sponsor_is_visible_sponsor_ribbon_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='ribbon_visible',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_pao_connected',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide the PAO ribbon', verbose_name='PAO Connection'),
        ),
    ]
