# Generated by Django 5.2.7 on 2026-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_remove_sponsor_ribbon_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('INSTITUTIONAL', 'Institutional'), ('COMMUNITY_PARTNER', 'Community Partner'), ('WELLNESS_PARTNER', 'Wellness Partner'), ('KEYSTONE', 'Keystone'), ('PLATINUM', 'Platinum'), ('TITANIUM', 'Titanium'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('COFFEE', 'Coffee')], max_length=255),
        ),
    ]
