# Generated by Django 5.2.7 on 2026-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_alter_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('INSTITUTIONAL', 'Institutional'), ('COMMUNITY_PARTNER', 'Community Partner'), ('WELLNESS_PARTNER', 'Wellness Partner'), ('KEYSTONE', 'Keystone'), ('PLATINUM', 'Platinum'), ('PLATINUM_PARTNER', 'Platinum Partner'), ('TITANIUM', 'Titanium'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('COFFEE', 'Coffee'), ('EDUCATION_SUMMIT', 'Education Summit')], max_length=255),
        ),
    ]
