SPONSOR_TYPE_ORDER = [
    "ORGANIZER",
    "INSTITUTIONAL",
    "KEYSTONE",
    "PLATINUM",
    "PLATINUM_PARTNER",
    "TITANIUM",
    "GOLD",
    "SILVER",
    "COMMUNITY_PARTNER",
    "WELLNESS_PARTNER",
    "COFFEE",
    "EDUCATION_SUMMIT",
]
