# Generated by Django 5.2.7 on 2026-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='modal_size',
            field=models.CharField(choices=[('md', 'Medium (default)'), ('lg', 'Large'), ('xl', 'Extra Large')], default='md', help_text='Width of the announcement modal', max_length=10),
        ),
    ]
