# Generated by Django 5.2.7 on 2026-03-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_modal_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibbonCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('cta_text', models.CharField(default='LEARN MORE', max_length=100)),
                ('cta_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ribbon CTA',
                'verbose_name_plural': 'Ribbon CTAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
