# Generated by Django 5.2.7 on 2026-03-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_ribboncta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Button CTA',
                'verbose_name_plural': 'Button CTAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
